# Nombre del workflow que aparecerá en la pestaña Actions
name: CI Pipeline

# Disparadores: el workflow se ejecutará en eventos 'push' y 'pull_request'
# para todas las ramas.
on: [push, pull_request]

# Trabajos a ejecutar
jobs:
  # Nombre del trabajo (puede ser cualquiera)
  build:
    # La máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Pasos que componen el trabajo
    steps:
      # Paso 1: Clona tu repositorio en la máquina virtual
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # Paso 2: Un paso de ejemplo para configurar el entorno
      - name: Configurar entorno
        run: echo "Configurando entorno de compilación..."

      # Paso 3: Un paso de ejemplo que simula una compilación
      - name: Compilar proyecto
        run: |
          echo "Ejecutando compilación..."
          echo "¡Compilación simulada exitosamente!"
